// The package root. `systemViewer` is deliberately absent: it is exported only from
// `@pangolin/app/system-viewer`, which lint bans outside `apps/server/src/{jobs,admin}` (AD-6).
export { fixedClock, fixedClockAt, systemClock } from "./clock.ts";
export type { UseCaseContext } from "./context.ts";
export {
  AppError,
  ERROR_CODES,
  type ErrorBody,
  type ErrorCode,
  errorBody,
  parseInput,
  validationError,
} from "./errors.ts";
export {
  type CreatePersonInput,
  createPerson,
  createPersonInput,
} from "./identity/create-person.ts";
export {
  type RecordCredentialChangeInput,
  recordCredentialChange,
} from "./identity/credentials.ts";
export {
  type ListLoginsInput,
  type Login,
  listLogins,
  listLoginsInput,
} from "./identity/list-logins.ts";
export {
  type AssertLoginAllowedInput,
  assertLoginAllowed,
  DEFAULT_LOCKOUT,
  type LockoutContext,
  type LockoutPolicy,
  lockedUntil,
  type RecordLoginAttemptInput,
  recordLoginAttempt,
} from "./identity/lockout.ts";
export {
  demoViewer,
  type EnrolmentStep,
  enrolmentNeeds,
  firstPerson,
  type Me,
  me,
  personForUser,
  sessionViewer,
} from "./identity/me.ts";
export {
  type DismissNoticeInput,
  dismissNotice,
  type ListNoticesInput,
  listNotices,
  type Notice,
} from "./identity/notices.ts";
export {
  type CheckReEnrolmentLinkInput,
  type ClearedCredentials,
  checkReEnrolmentLink,
  type IssuedReEnrolmentLink,
  type IssueReEnrolmentLinkInput,
  invalidReEnrolmentLink,
  issueReEnrolmentLink,
  PARTNER_RESET_REVIEW,
  partnerResetDedupeKey,
  RE_ENROLMENT_LINK_TTL_MS,
  type RedeemedReEnrolmentLink,
  type RedeemReEnrolmentLinkInput,
  type ReEnrolmentContext,
  redeemReEnrolmentLink,
  reEnrolmentUrl,
  revokeMyReEnrolmentLinks,
} from "./identity/re-enrolment.ts";
export { REAUTH_WINDOW_MS, requireRecentAuth } from "./identity/reauth.ts";
export {
  formatRecoveryCode,
  type IssuedRecoveryCodes,
  type IssueInitialRecoveryCodesInput,
  issueInitialRecoveryCodes,
  normaliseRecoveryCode,
  RECOVERY_CODE_ALPHABET,
  RECOVERY_CODE_COUNT,
  RECOVERY_CODE_LENGTH,
  RECOVERY_CODE_USED_REVIEW,
  type RecoveryCodeContext,
  type RedeemedRecoveryCode,
  type RedeemRecoveryCodeInput,
  type RegenerateRecoveryCodesInput,
  recoveryRefused,
  redeemRecoveryCode,
  regenerateRecoveryCodes,
} from "./identity/recovery-codes.ts";
export {
  RESET_USER_ACTOR,
  type ResetUserInput,
  type ResetUserResult,
  resetUser,
} from "./identity/reset-user.ts";
export {
  type EnsureFirstSetupLinkInput,
  ensureFirstSetupLink,
  type FirstSetupLink,
  type IssuedSetupLink,
  type IssueSetupLinkInput,
  issueSetupLink,
  MAX_USERS,
  SETUP_LINK_TTL_MS,
  type SetupLinkContext,
} from "./identity/setup-links.ts";
export {
  type CheckSignUpInput,
  type CompleteSignUpInput,
  checkSignUp,
  completeSignUp,
  type IdentityContext,
} from "./identity/sign-up.ts";
export { createIdGenerator, type IdGenerator, type IdSources, newId } from "./ids.ts";
export { type EnqueueOptions, enqueueJob } from "./jobs/enqueue.ts";
export {
  type CancelJobsForRestoreInput,
  type ClaimInput,
  type CompleteInput,
  cancelJobsForRestore,
  claimJob,
  completeJob,
  ensureSchedules,
  type FailInput,
  type FailOutcome,
  failJob,
  RESTORED_REASON,
  renewJobLease,
} from "./jobs/lifecycle.ts";
export {
  backoffMs,
  DEFAULT_RETRY,
  defineJobKind,
  defineSchedule,
  JOB_LANES,
  type JobContext,
  type JobHandler,
  type JobKind,
  type JobKindSpec,
  type JobRegistration,
  type JobSignal,
  jobHandler,
  type RetryPolicy,
  type Schedule,
  scheduleKey,
} from "./jobs/registry.ts";
export type { Clock } from "./ports/clock.ts";
export type { SystemHealthPort } from "./ports/system-health.ts";
export type { CodeHasher, TokenPort } from "./ports/tokens.ts";
export type {
  AuditRepo,
  AuditRow,
  BackupSnapshotRepo,
  BackupSnapshotRow,
  BackupVerificationKind,
  BackupVerificationRepo,
  BackupVerificationRow,
  CredentialRepo,
  DeadJobRow,
  HouseholdSettingsRepo,
  HouseholdSettingsRow,
  JobLane,
  JobRepo,
  JobRow,
  JobStatus,
  LoginAttemptRepo,
  LoginAttemptRow,
  LoginRow,
  PersonRepo,
  PersonRow,
  ReadRepos,
  RecoveryCodeCounts,
  RecoveryCodeRepo,
  RecoveryCodeRow,
  ReEnrolmentLinkRepo,
  ReEnrolmentLinkRow,
  ReviewItemRepo,
  ReviewItemRow,
  SetupLinkRepo,
  SetupLinkRow,
  TxRepos,
  UnitOfWork,
  UserEnrolment,
  UserRepo,
} from "./ports/unit-of-work.ts";
export {
  BACKUP_CHECK_JOB,
  BACKUP_CHECK_SCHEDULE_NAME,
  BACKUP_CHECK_TIME,
  BACKUP_DRILL_JOB,
  BACKUP_DRILL_SCHEDULE_NAME,
  BACKUP_DRILL_TIME,
  BACKUP_PUSH_JOB,
  BACKUP_SCHEDULE_NAME,
  BACKUP_SNAPSHOT_JOB,
  BACKUP_TIME,
  BACKUP_VERIFICATION_FAILED_REVIEW,
  type BackupProgress,
  type BackupProgressInput,
  type BackupStatus,
  type BackupVerification,
  backupCheckSchedule,
  backupDrillSchedule,
  backupFreshness,
  backupProgress,
  backupProgressInput,
  backupStatus,
  backupsAwaitingPush,
  backupsAwaitingPushInput,
  dailyAt,
  getBackupSnapshot,
  getBackupSnapshotInput,
  type LastBackup,
  lastBackup,
  MANUAL_BACKUP_KEY,
  monthlyAt,
  nightlyBackupSchedule,
  type RecordBackupPushInput,
  type RecordBackupSnapshotInput,
  type RecordBackupVerificationInput,
  type RecordedBackupPush,
  recordBackupPush,
  recordBackupPushInput,
  recordBackupSnapshot,
  recordBackupSnapshotInput,
  recordBackupVerification,
  recordBackupVerificationInput,
  requestBackup,
  STALE_BACKUP_MS,
  weeklyAt,
} from "./system/backups.ts";
export {
  type HealthContext,
  type HealthInput,
  type HealthOutput,
  health,
  healthInput,
} from "./system/health.ts";
export {
  type GetHouseholdSettingsInput,
  getHouseholdSettings,
  getHouseholdSettingsInput,
  type HouseholdSettings,
  type UpdateHouseholdSettingsInput,
  updateHouseholdSettings,
  updateHouseholdSettingsInput,
} from "./system/household-settings.ts";
export {
  DEAD_JOBS_LIMIT,
  type DeadJob,
  type DeadJobsInput,
  deadJobs,
  deadJobsInput,
  type JobCounts,
  type JobCountsInput,
  type JobStatusContext,
  jobCounts,
  jobCountsInput,
} from "./system/job-status.ts";
export {
  READINESS_CHECKS,
  type ReadinessCheck,
  type ReadinessContext,
  type ReadinessInput,
  type ReadinessOutput,
  type ReadinessWarning,
  RUNNER_STALE_POLLS,
  type RunnerLiveness,
  readiness,
  readinessInput,
} from "./system/readiness.ts";
export {
  defineReviewKind,
  JOB_DEAD_REVIEW,
  type ListReviewItemsInput,
  listReviewItems,
  listReviewItemsInput,
  type RaiseReviewItemInput,
  type ResolveReviewItemInput,
  type ReviewItem,
  type ReviewKind,
  type ReviewScope,
  raiseReviewItem,
  resolveReviewItem,
  UPGRADE_FAILED_REVIEW,
} from "./system/review-items.ts";
export {
  actorOf,
  type PersonViewer,
  personViewer,
  type SystemActor,
  type SystemViewer,
  type Viewer,
} from "./viewer.ts";
export { type Audit, type AuditEntry, write } from "./write.ts";
