// The package root. `systemViewer` is deliberately absent: it is exported only from
// `@pangolin/app/system-viewer`, which lint bans outside `apps/server/src/{jobs,admin}` (AD-6).

export {
  checkSeedReferences,
  emptySeedKnown,
  type SeedKnown,
  type SeedReferenceEvent,
} from "@pangolin/shared/seed";
export {
  type BalanceAsOfInput,
  balanceAsOf,
  balanceAsOfInput,
  CASH_ACCOUNT_TYPES,
  type ListBalanceSnapshotsInput,
  listBalanceSnapshots,
  listBalanceSnapshotsInput,
  type RecordBalanceSnapshotInput,
  recordBalanceSnapshot,
  recordBalanceSnapshotInput,
} from "./accounts/balance.ts";
export {
  type CloseAccountInput,
  closeAccount,
  closeAccountInput,
} from "./accounts/close-account.ts";
export {
  type CreateAccountInput,
  createAccount,
  createAccountInput,
} from "./accounts/create-account.ts";
export {
  type CreateInstitutionInput,
  createInstitution,
  createInstitutionInput,
  listInstitutions,
  type UpdateInstitutionInput,
  updateInstitution,
  updateInstitutionInput,
} from "./accounts/institutions.ts";
export {
  type GetAccountInput,
  getAccount,
  getAccountInput,
  type ListAccountsInput,
  listAccounts,
  listAccountsInput,
} from "./accounts/list-accounts.ts";
export { type AccountView, payerOf, poolOf } from "./accounts/pool.ts";
export { type SetPrivacyInput, setPrivacy, setPrivacyInput } from "./accounts/set-privacy.ts";
export {
  type UpdateAccountInput,
  updateAccount,
  updateAccountInput,
} from "./accounts/update-account.ts";
export {
  type CreateActivityInput,
  createActivity,
  createActivityInput,
  type DeleteActivityInput,
  deleteActivity,
  deleteActivityInput,
  getActivity,
  getActivityInput,
  listActivities,
  type UpdateActivityInput,
  updateActivity,
  updateActivityInput,
} from "./classify/activities.ts";
export {
  type CreateCategoryInput,
  createCategory,
  createCategoryInput,
  type DeleteCategoryInput,
  deleteCategory,
  deleteCategoryInput,
  listCategories,
  type UpdateCategoryInput,
  updateCategory,
  updateCategoryInput,
} from "./classify/categories.ts";
export {
  type CreateCategoryGroupInput,
  createCategoryGroup,
  createCategoryGroupInput,
  listCategoryGroups,
  type UpdateCategoryGroupInput,
  updateCategoryGroup,
  updateCategoryGroupInput,
} from "./classify/category-groups.ts";
export {
  DEFAULT_CATEGORIES,
  DEFAULT_TAX_CATEGORIES,
  seedDefaults,
} from "./classify/defaults.ts";
export {
  type CreatePayeeAliasInput,
  type CreatePayeeInput,
  createPayee,
  createPayeeAlias,
  createPayeeAliasInput,
  createPayeeInput,
  deletePayee,
  deletePayeeAlias,
  deletePayeeAliasInput,
  deletePayeeInput,
  getPayee,
  getPayeeAlias,
  getPayeeAliasInput,
  getPayeeInput,
  listPayeeAliases,
  listPayees,
  MAX_ALIAS_PATTERN_LENGTH,
  type UpdatePayeeAliasInput,
  type UpdatePayeeInput,
  updatePayee,
  updatePayeeAlias,
  updatePayeeAliasInput,
  updatePayeeInput,
} from "./classify/payees.ts";
export { type Scope, scopeFor } from "./classify/scope.ts";
export {
  type CreateTagInput,
  createTag,
  createTagInput,
  type DeleteTagInput,
  deleteTag,
  deleteTagInput,
  getTag,
  getTagInput,
  listTags,
  type UpdateTagInput,
  updateTag,
  updateTagInput,
} from "./classify/tags.ts";
export {
  type CreateTaxCategoryInput,
  createTaxCategory,
  createTaxCategoryInput,
  listTaxCategories,
  type UpdateTaxCategoryInput,
  updateTaxCategory,
  updateTaxCategoryInput,
} from "./classify/tax-categories.ts";
export { fixedClock, fixedClockAt, systemClock } from "./clock.ts";
export type { UseCaseContext } from "./context.ts";
export {
  AppError,
  ERROR_CODES,
  type ErrorBody,
  type ErrorCode,
  errorBody,
  parseInput,
  validationError,
} from "./errors.ts";
export {
  type CreatePersonInput,
  createPerson,
  createPersonInput,
} from "./identity/create-person.ts";
export {
  type RecordCredentialChangeInput,
  recordCredentialChange,
} from "./identity/credentials.ts";
export {
  type ListLoginsInput,
  type Login,
  listLogins,
  listLoginsInput,
} from "./identity/list-logins.ts";
export {
  type AssertLoginAllowedInput,
  assertLoginAllowed,
  DEFAULT_LOCKOUT,
  type LockoutContext,
  type LockoutPolicy,
  lockedUntil,
  type RecordLoginAttemptInput,
  recordLoginAttempt,
  releaseLoginAttempt,
  reserveLoginAttempt,
} from "./identity/lockout.ts";
export {
  demoViewer,
  type EnrolmentStep,
  enrolmentNeeds,
  firstPerson,
  type Me,
  me,
  personForUser,
  sessionViewer,
} from "./identity/me.ts";
export {
  type DismissNoticeInput,
  dismissNotice,
  type ListNoticesInput,
  listNotices,
  type Notice,
} from "./identity/notices.ts";
export {
  type CheckReEnrolmentLinkInput,
  type ClearedCredentials,
  checkReEnrolmentLink,
  clearCredentials,
  type IssuedReEnrolmentLink,
  type IssueReEnrolmentLinkInput,
  invalidReEnrolmentLink,
  issueReEnrolmentLink,
  PARTNER_RESET_REVIEW,
  partnerResetDedupeKey,
  RE_ENROLMENT_LINK_TTL_MS,
  type RedeemedReEnrolmentLink,
  type RedeemReEnrolmentLinkInput,
  type ReEnrolmentContext,
  redeemReEnrolmentLink,
  reEnrolmentUrl,
  revokeMyReEnrolmentLinks,
} from "./identity/re-enrolment.ts";
export { REAUTH_WINDOW_MS, requireRecentAuth } from "./identity/reauth.ts";
export {
  formatRecoveryCode,
  type IssuedRecoveryCodes,
  type IssueInitialRecoveryCodesInput,
  issueInitialRecoveryCodes,
  normaliseRecoveryCode,
  RECOVERY_CODE_ALPHABET,
  RECOVERY_CODE_COUNT,
  RECOVERY_CODE_LENGTH,
  RECOVERY_CODE_USED_REVIEW,
  type RecoveryCodeContext,
  type RedeemedRecoveryCode,
  type RedeemRecoveryCodeInput,
  type RegenerateRecoveryCodesInput,
  recoveryRefused,
  redeemRecoveryCode,
  regenerateRecoveryCodes,
} from "./identity/recovery-codes.ts";
export {
  RESET_USER_ACTOR,
  type ResetUserInput,
  type ResetUserResult,
  resetUser,
} from "./identity/reset-user.ts";
export {
  type EnsureFirstSetupLinkInput,
  ensureFirstSetupLink,
  type FirstSetupLink,
  type IssuedSetupLink,
  type IssueSetupLinkInput,
  issueSetupLink,
  MAX_USERS,
  SETUP_LINK_TTL_MS,
  type SetupLinkContext,
} from "./identity/setup-links.ts";
export {
  type CheckSignUpInput,
  type CompleteSignUpInput,
  checkSignUp,
  completeSignUp,
  type IdentityContext,
} from "./identity/sign-up.ts";
export { createIdGenerator, type IdGenerator, type IdSources, newId } from "./ids.ts";
export { type EnqueueOptions, enqueueJob } from "./jobs/enqueue.ts";
export {
  type CancelJobsForRestoreInput,
  type ClaimInput,
  type CompleteInput,
  cancelJobsForRestore,
  claimJob,
  completeJob,
  ensureSchedules,
  type FailInput,
  type FailOutcome,
  failJob,
  RESTORED_REASON,
  renewJobLease,
} from "./jobs/lifecycle.ts";
export {
  backoffMs,
  DEFAULT_RETRY,
  defineJobKind,
  defineSchedule,
  JOB_LANES,
  type JobContext,
  type JobHandler,
  type JobKind,
  type JobKindSpec,
  type JobRegistration,
  type JobSignal,
  jobHandler,
  type RetryPolicy,
  type Schedule,
  scheduleKey,
} from "./jobs/registry.ts";
export {
  type CreateTransactionInput,
  createTransaction,
  createTransactionInput,
} from "./ledger/create-transaction.ts";
export {
  type DeleteTransactionInput,
  deleteTransaction,
  deleteTransactionInput,
} from "./ledger/delete-transaction.ts";
export {
  type GetTransactionInput,
  getTransaction,
  getTransactionInput,
} from "./ledger/get-transaction.ts";
export {
  type HideTransactionNameInput,
  hideTransactionName,
  hideTransactionNameInput,
  MAX_HIDE_MONTHS,
  type UnhideTransactionNameInput,
  unhideTransactionName,
  unhideTransactionNameInput,
} from "./ledger/hide-name.ts";
export {
  type LedgerSplit,
  type LedgerTransaction,
  type ListTransactionsInput,
  listTransactions,
  listTransactionsInput,
} from "./ledger/list-transactions.ts";
export {
  mayOverwrite,
  sourceRank,
} from "./ledger/provenance.ts";
export {
  registerSplitFieldListener,
  type SetSplitFieldInput,
  type SetSplitFieldResult,
  SPLIT_FIELDS,
  type SplitField,
  type SplitFieldListener,
  type SplitFieldWrite,
  setSplitField,
  setSplitFieldInput,
} from "./ledger/set-split-field.ts";
export {
  MAX_SPLITS,
  type SetSplitsInput,
  setSplits,
  setSplitsInput,
} from "./ledger/set-splits.ts";
export {
  type SetSplitTagsInput,
  setSplitTags,
  setSplitTagsInput,
} from "./ledger/split-tags.ts";
export { remainingCents } from "./ledger/transaction-view.ts";
export {
  type CreateTransferGroupInput,
  createTransferGroup,
  createTransferGroupInput,
  type DeleteTransferGroupInput,
  deleteTransferGroup,
  deleteTransferGroupInput,
} from "./ledger/transfer-groups.ts";
export {
  type UpdateTransactionInput,
  updateTransaction,
  updateTransactionInput,
} from "./ledger/update-transaction.ts";
export type { Clock } from "./ports/clock.ts";
export type { SystemHealthPort } from "./ports/system-health.ts";
export type { CodeHasher, TokenPort } from "./ports/tokens.ts";
export type {
  AuditRepo,
  AuditRow,
  AuditView,
  BackupSnapshotRepo,
  BackupSnapshotRow,
  BackupVerificationKind,
  BackupVerificationRepo,
  BackupVerificationRow,
  CredentialRepo,
  DeadJobRow,
  HouseholdSettingsRepo,
  HouseholdSettingsRow,
  JobLane,
  JobRepo,
  JobRow,
  JobStatus,
  LoginAttemptRepo,
  LoginAttemptRow,
  LoginRow,
  PendingJobRow,
  PersonRepo,
  PersonRow,
  ReadRepos,
  RecoveryBundleRepo,
  RecoveryBundleRow,
  RecoveryCodeCounts,
  RecoveryCodeRepo,
  RecoveryCodeRow,
  ReEnrolmentLinkRepo,
  ReEnrolmentLinkRow,
  ReviewItemRepo,
  ReviewItemRow,
  RunningJobRow,
  SetupLinkRepo,
  SetupLinkRow,
  TxRepos,
  UnitOfWork,
  UserEnrolment,
  UserRepo,
} from "./ports/unit-of-work.ts";
export {
  ACCOUNT_TYPES,
  type AccountOwnerRow,
  type AccountRepo,
  type AccountRow,
  type AccountType,
  type ActivityRepo,
  type ActivityRow,
  ALIAS_MATCH_KINDS,
  type AliasMatchKind,
  BALANCE_SOURCES,
  type BalanceSnapshotRepo,
  type BalanceSnapshotRow,
  type BalanceSource,
  CATEGORY_GROUP_KINDS,
  type CategoryGroupKind,
  type CategoryGroupRepo,
  type CategoryGroupRow,
  type CategoryRepo,
  type CategoryRow,
  INSTITUTION_KINDS,
  type InstitutionKind,
  type InstitutionRepo,
  type InstitutionRow,
  type PayeeAliasRepo,
  type PayeeAliasRow,
  type PayeeRepo,
  type PayeeRow,
  type ScopedRows,
  SPLIT_SOURCES,
  type SplitRow,
  type SplitSource,
  type SplitTagged,
  type SplitTagRow,
  type TagRepo,
  type TagRow,
  type TaxCategoryRepo,
  type TaxCategoryRow,
  TRANSFER_MATCHES,
  type TransactionRepo,
  type TransactionRow,
  type TransactionWithSplits,
  type TransferGroupRepo,
  type TransferGroupRow,
  type TransferMatch,
  type VisibleTransaction,
} from "./ports/unit-of-work.ts";
export { hiddenLabel, redact } from "./redact.ts";
export {
  BACKUP_CHECK_JOB,
  BACKUP_CHECK_SCHEDULE_NAME,
  BACKUP_CHECK_TIME,
  BACKUP_DRILL_JOB,
  BACKUP_DRILL_SCHEDULE_NAME,
  BACKUP_DRILL_TIME,
  BACKUP_PUSH_JOB,
  BACKUP_SCHEDULE_NAME,
  BACKUP_SNAPSHOT_JOB,
  BACKUP_TIME,
  BACKUP_VERIFICATION_FAILED_REVIEW,
  type BackupProgress,
  type BackupProgressInput,
  type BackupStatus,
  type BackupVerification,
  backupCheckSchedule,
  backupDrillSchedule,
  backupFreshness,
  backupProgress,
  backupProgressInput,
  backupStatus,
  backupsAwaitingPush,
  backupsAwaitingPushInput,
  dailyAt,
  getBackupSnapshot,
  getBackupSnapshotInput,
  type LastBackup,
  lastBackup,
  MANUAL_BACKUP_KEY,
  monthlyAt,
  nightlyBackupSchedule,
  type RecordBackupPushInput,
  type RecordBackupSnapshotInput,
  type RecordBackupVerificationInput,
  type RecordedBackupPush,
  recordBackupPush,
  recordBackupPushInput,
  recordBackupSnapshot,
  recordBackupSnapshotInput,
  recordBackupVerification,
  recordBackupVerificationInput,
  requestBackup,
  STALE_BACKUP_MS,
  weeklyAt,
} from "./system/backups.ts";
export {
  type HealthContext,
  type HealthInput,
  type HealthOutput,
  health,
  healthInput,
} from "./system/health.ts";
export {
  type GetHouseholdSettingsInput,
  getHouseholdSettings,
  getHouseholdSettingsInput,
  type HouseholdSettings,
  type UpdateHouseholdSettingsInput,
  updateHouseholdSettings,
  updateHouseholdSettingsInput,
} from "./system/household-settings.ts";
export {
  DEAD_JOBS_LIMIT,
  type DeadJob,
  type DeadJobsInput,
  deadJobs,
  deadJobsInput,
  type JobCounts,
  type JobCountsInput,
  type JobStatusContext,
  jobCounts,
  jobCountsInput,
  type PendingJob,
  type PendingJobsInput,
  pendingJobs,
  pendingJobsInput,
  QUEUED_JOBS_LIMIT,
  type RunningJob,
  type RunningJobsInput,
  runningJobs,
  runningJobsInput,
} from "./system/job-status.ts";
export { type ListAuditInput, listAudit, listAuditInput } from "./system/list-audit.ts";
export {
  READINESS_CHECKS,
  type ReadinessCheck,
  type ReadinessContext,
  type ReadinessInput,
  type ReadinessOutput,
  type ReadinessWarning,
  RUNNER_STALE_POLLS,
  type RunnerLiveness,
  readiness,
  readinessInput,
} from "./system/readiness.ts";
export {
  type ConfirmedRecoveryBundle,
  type ConfirmRecoveryBundleInput,
  confirmRecoveryBundle,
  confirmRecoveryBundleInput,
  NO_RECOVERY_BUNDLE_ID,
  RECOVERY_BUNDLE_ID_PATTERN,
  type RecoveryBundleStatus,
  recoveryBundleConfirmed,
  recoveryBundleId,
  recoveryBundleStatus,
} from "./system/recovery-bundle.ts";
export {
  defineReviewKind,
  type EntitySyncListener,
  JOB_DEAD_REVIEW,
  type ListReviewItemsInput,
  listReviewItems,
  listReviewItemsInput,
  type RaiseReviewItemInput,
  RESTORED_REVIEW,
  type ResolveReviewItemInput,
  type ResolveReviewItemsForEntityInput,
  type ReviewItem,
  type ReviewKind,
  type ReviewScope,
  raiseReviewItem,
  registerEntitySync,
  resolveReviewItem,
  resolveReviewItemsForEntity,
  UPGRADE_FAILED_REVIEW,
} from "./system/review-items.ts";
export {
  actorOf,
  type PersonViewer,
  personViewer,
  type SystemActor,
  type SystemViewer,
  type Viewer,
} from "./viewer.ts";
export { type Audit, type AuditEntry, write } from "./write.ts";
